/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package gestionavancecurricular;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.SwingConstants;

/**
 *
 * @author Vicente
 */
public class VentanaAdmin extends javax.swing.JFrame {
    private ArrayList<Alumno> listaAlumnos;
    private ArrayList<Profesor> listaProfesores;
    private ArrayList<Asignatura> listaAsignaturas;
    
    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin(ArrayList<Alumno> lsAlumm, ArrayList<Profesor> lsProf, ArrayList<Asignatura> lsAsig) {
        initComponents();
        
        listaAlumnos = lsAlumm;
        listaProfesores = lsProf;
        listaAsignaturas = lsAsig;
        
        jPanel1.setBackground(new Color(165,161,157));
        
        mnu_alumno.setText("                        Alumno                        ");
        mnu_profesor.setText("                        Profesor                        ");
        mnu_asignatura.setText("                        Asignatura                        ");
        
        mnu_alumno.setForeground(new Color(39,32,24));
        
        btn_volver.setText("Volver");
        btn_volver.setBackground(Color.DARK_GRAY);
        btn_volver.setForeground(Color.WHITE);
        btn_volver.setHorizontalAlignment(SwingConstants.CENTER);
        
        mnu_alumno.setForeground(Color.BLUE);
        mnu_profesor.setForeground(Color.BLUE);
        mnu_asignatura.setForeground(Color.BLUE);
        
        itm_agregarAlumno.setText("                  Agregar Alumno        ");
        itm_buscarAlumno.setText("                  Buscar Alumno        ");
        itm_actualizarAlumno.setText("                  Actualizar Alumno        ");
        itm_borrarAlumno.setText("                  Borrar Alumno        ");
        
        itm_agregarProfesor.setText("                  Agregar Profesor        ");
        itm_buscarProfesor.setText("                  Buscar Profesor        ");
        itm_actualizarProfesor.setText("                  Actualizar Profesor        ");
        itm_borrarProfesor.setText("                  Borrar Profesor        ");
        
        itm_agregarAsignatura.setText("                  Agregar Asignatura        ");
        itm_buscarAsignatura.setText("                  Buscar Asignatura        ");
        itm_actualizarAsignatura.setText("                  Actualizar Asignatura        ");
        itm_borrarAsignatura.setText("                  Borrar Asignatura        ");
        
        lbl_titulo.setFont(new Font("colibri",Font.BOLD,20));
        lbl_titulo.setText("Bienvenido Admin !");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_volver = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnu_alumno = new javax.swing.JMenu();
        itm_agregarAlumno = new javax.swing.JMenuItem();
        itm_buscarAlumno = new javax.swing.JMenuItem();
        itm_actualizarAlumno = new javax.swing.JMenuItem();
        itm_borrarAlumno = new javax.swing.JMenuItem();
        mnu_profesor = new javax.swing.JMenu();
        itm_agregarProfesor = new javax.swing.JMenuItem();
        itm_buscarProfesor = new javax.swing.JMenuItem();
        itm_actualizarProfesor = new javax.swing.JMenuItem();
        itm_borrarProfesor = new javax.swing.JMenuItem();
        mnu_asignatura = new javax.swing.JMenu();
        itm_agregarAsignatura = new javax.swing.JMenuItem();
        itm_buscarAsignatura = new javax.swing.JMenuItem();
        itm_actualizarAsignatura = new javax.swing.JMenuItem();
        itm_borrarAsignatura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mnu_alumno.setMnemonic('f');

        itm_agregarAlumno.setMnemonic('o');
        itm_agregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_agregarAlumnoActionPerformed(evt);
            }
        });
        mnu_alumno.add(itm_agregarAlumno);

        itm_buscarAlumno.setMnemonic('s');
        itm_buscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_buscarAlumnoActionPerformed(evt);
            }
        });
        mnu_alumno.add(itm_buscarAlumno);

        itm_actualizarAlumno.setMnemonic('a');
        itm_actualizarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_actualizarAlumnoActionPerformed(evt);
            }
        });
        mnu_alumno.add(itm_actualizarAlumno);

        itm_borrarAlumno.setMnemonic('x');
        itm_borrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_borrarAlumnoActionPerformed(evt);
            }
        });
        mnu_alumno.add(itm_borrarAlumno);

        menuBar.add(mnu_alumno);

        mnu_profesor.setMnemonic('e');

        itm_agregarProfesor.setMnemonic('o');
        itm_agregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_agregarProfesorActionPerformed(evt);
            }
        });
        mnu_profesor.add(itm_agregarProfesor);

        itm_buscarProfesor.setMnemonic('s');
        itm_buscarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_buscarProfesorActionPerformed(evt);
            }
        });
        mnu_profesor.add(itm_buscarProfesor);

        itm_actualizarProfesor.setMnemonic('a');
        itm_actualizarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_actualizarProfesorActionPerformed(evt);
            }
        });
        mnu_profesor.add(itm_actualizarProfesor);

        itm_borrarProfesor.setMnemonic('x');
        itm_borrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_borrarProfesorActionPerformed(evt);
            }
        });
        mnu_profesor.add(itm_borrarProfesor);

        menuBar.add(mnu_profesor);

        mnu_asignatura.setMnemonic('h');

        itm_agregarAsignatura.setMnemonic('o');
        itm_agregarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_agregarAsignaturaActionPerformed(evt);
            }
        });
        mnu_asignatura.add(itm_agregarAsignatura);

        itm_buscarAsignatura.setMnemonic('s');
        itm_buscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_buscarAsignaturaActionPerformed(evt);
            }
        });
        mnu_asignatura.add(itm_buscarAsignatura);

        itm_actualizarAsignatura.setMnemonic('a');
        itm_actualizarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_actualizarAsignaturaActionPerformed(evt);
            }
        });
        mnu_asignatura.add(itm_actualizarAsignatura);

        itm_borrarAsignatura.setMnemonic('x');
        itm_borrarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_borrarAsignaturaActionPerformed(evt);
            }
        });
        mnu_asignatura.add(itm_borrarAsignatura);

        menuBar.add(mnu_asignatura);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void itm_agregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_agregarAlumnoActionPerformed
        VentanaAgregarAlumno ventanaAgrAlumno = new VentanaAgregarAlumno(listaAlumnos);
        ventanaAgrAlumno.setVisible(true);
    }//GEN-LAST:event_itm_agregarAlumnoActionPerformed

    private void itm_buscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_buscarAlumnoActionPerformed
        VentanaBuscarAlumno ventanaBuscarAlumno = new VentanaBuscarAlumno(listaAlumnos);
        ventanaBuscarAlumno.setVisible(true);
    }//GEN-LAST:event_itm_buscarAlumnoActionPerformed

    private void itm_actualizarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_actualizarAlumnoActionPerformed
        VentanaActualizarAlumno ventanaActAlumno = new VentanaActualizarAlumno(listaAlumnos);
        ventanaActAlumno.setVisible(true);
    }//GEN-LAST:event_itm_actualizarAlumnoActionPerformed

    private void itm_borrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_borrarAlumnoActionPerformed
        VentanaBorrarAlumno ventanaBorrAlumno = new VentanaBorrarAlumno(listaAlumnos,listaAsignaturas);
        ventanaBorrAlumno.setVisible(true);
    }//GEN-LAST:event_itm_borrarAlumnoActionPerformed

    private void itm_agregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_agregarProfesorActionPerformed
        VentanaAgregarProfesor ventanaAgrProfesor = new VentanaAgregarProfesor(listaProfesores);
        ventanaAgrProfesor.setVisible(true);
    }//GEN-LAST:event_itm_agregarProfesorActionPerformed

    private void itm_buscarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_buscarProfesorActionPerformed
        VentanaBuscarProfesor ventanaBuscarProfesor = new VentanaBuscarProfesor(listaProfesores);
        ventanaBuscarProfesor.setVisible(true);
    }//GEN-LAST:event_itm_buscarProfesorActionPerformed

    private void itm_actualizarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_actualizarProfesorActionPerformed
        VentanaActualizarProfesor ventanaActProfesor = new VentanaActualizarProfesor(listaProfesores);
        ventanaActProfesor.setVisible(true);
    }//GEN-LAST:event_itm_actualizarProfesorActionPerformed

    private void itm_borrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_borrarProfesorActionPerformed
        VentanaBorrarProfesor ventanaBorrProfesor = new VentanaBorrarProfesor(listaProfesores, listaAsignaturas);
        ventanaBorrProfesor.setVisible(true);
    }//GEN-LAST:event_itm_borrarProfesorActionPerformed

    private void itm_agregarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_agregarAsignaturaActionPerformed
        VentanaAgregarAsignatura ventanaAgrAsignatura = new VentanaAgregarAsignatura(listaAsignaturas, listaProfesores);
        ventanaAgrAsignatura.setVisible(true);
    }//GEN-LAST:event_itm_agregarAsignaturaActionPerformed

    private void itm_buscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_buscarAsignaturaActionPerformed
        VentanaBuscarAsignatura ventanaBuscarAsignatura = new VentanaBuscarAsignatura(listaAsignaturas);
        ventanaBuscarAsignatura.setVisible(true);
    }//GEN-LAST:event_itm_buscarAsignaturaActionPerformed

    private void itm_actualizarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_actualizarAsignaturaActionPerformed
        VentanaActualizarAsignatura ventanaActAsignatura = new VentanaActualizarAsignatura(listaAsignaturas);
        ventanaActAsignatura.setVisible(true);
    }//GEN-LAST:event_itm_actualizarAsignaturaActionPerformed

    private void itm_borrarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_borrarAsignaturaActionPerformed
        VentanaBorrarAsignatura ventanaBorrAsignatura = new VentanaBorrarAsignatura(listaAsignaturas);
        ventanaBorrAsignatura.setVisible(true);
    }//GEN-LAST:event_itm_borrarAsignaturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_volver;
    private javax.swing.JMenuItem itm_actualizarAlumno;
    private javax.swing.JMenuItem itm_actualizarAsignatura;
    private javax.swing.JMenuItem itm_actualizarProfesor;
    private javax.swing.JMenuItem itm_agregarAlumno;
    private javax.swing.JMenuItem itm_agregarAsignatura;
    private javax.swing.JMenuItem itm_agregarProfesor;
    private javax.swing.JMenuItem itm_borrarAlumno;
    private javax.swing.JMenuItem itm_borrarAsignatura;
    private javax.swing.JMenuItem itm_borrarProfesor;
    private javax.swing.JMenuItem itm_buscarAlumno;
    private javax.swing.JMenuItem itm_buscarAsignatura;
    private javax.swing.JMenuItem itm_buscarProfesor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnu_alumno;
    private javax.swing.JMenu mnu_asignatura;
    private javax.swing.JMenu mnu_profesor;
    // End of variables declaration//GEN-END:variables

}
